version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - /home/The-BangerTECH-Utility-main/docker-compose-data/grafana/data/env.grafana
    user: "root"
    volumes:
      - /home/The-BangerTECH-Utility-main/docker-compose-data/grafana/data:/var/lib/grafana