version: '3'
services:
  webdock-ui:
    image: bangertech/webdock:latest
    container_name: webdock-ui
    user: "999:999"
    ports:
      - "8585:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - CONFIG_DIR=/app/config
      - DOCKER_GID=999
    restart: unless-stopped 