services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    networks:
      - webdock-network
    restart: unless-stopped
    ports:
      # Host Port:Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data

    environment:
      # Tell Dockge where is your stacks directory
networks:
  webdock-network:
    external: true