categories:
  monitoring:
    containers: []
    description: System and network monitoring tools
    icon: fa-chart-line
    name: Monitoring
  smart_home:
    containers: []
    description: Home automation and IoT containers
    icon: fa-home
    name: Smart Home
