categories:
  bridge:
    containers:
    - homebridge
    - mosquitto-broker
    - zigbee2mqtt
    description: IoT bridges and communication
    icon: fa-exchange
    name: Bridge
  dashboard:
    containers:
    - heimdall
    - grafana
    description: Visualization and monitoring dashboards
    icon: fa-th-large
    name: Dashboard
  other:
    containers:
    - whatsupdocker
    - watchyourlan
    - webdock-ui
    - filestash
    description: Additional containers and tools
    icon: fa-ellipsis-h
    name: Other
  service:
    containers:
    - filebrowser
    - codeserver
    - frontail
    - nodeexporter
    - portainer
    - dockge
    - prometheus
    description: System services and tools
    icon: fa-cogs
    name: Service
  smarthome:
    containers:
    - openhab
    - homeassistant
    - raspberrymatic
    description: Home automation systems
    icon: fa-home
    name: Smart Home
