---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          icon: github.png
          href: https://github.com/BangerTech

- Social:
    - Reddit:
        - abbr: RE
          icon: reddit.png
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          icon: youtube.png
          href: https://www.youtube.com/@bangertech
