
services:
  frontend:
    image: bangertech/bambucam-frontend:latest
    restart: unless-stopped
    network_mode: "host"

  backend:
    image: bangertech/bambucam-backend:latest
    restart: unless-stopped
    volumes:
      - bambucam_data:/app/data
      - bambucam_logs:/app/logs
    network_mode: "host"

  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    restart: unless-stopped
    network_mode: host
    volumes:
      - bambucam_go2rtc:/config
    environment:
      - GO2RTC_CONFIG=/config/go2rtc.yaml
      - GO2RTC_API=listen=:1984
      - GO2RTC_API_BASE=/go2rtc

volumes:
  bambucam_logs:
  bambucam_data:
  bambucam_go2rtc: