services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    networks:
      - webdock-network
    restart: always
    ports:
      - 8999:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
volumes:
  portainer_data:
networks:
  webdock-network:
    external: true