services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - webdock-network
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped


volumes:
  prometheus-data:

networks:
  webdock-network:
    external: true
