services:
  influxdb:
    # Raspberry Pi Image
    image: hypriot/rpi-influxdb
    container_name: influxdb
    networks:
      - webdock-network
    restart: always
    volumes:
      - ./data:/var/lib/influxdb
    ports:
      - "8086:8086"
networks:
  webdock-network:
    external: true