services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    networks:
      - webdock-network
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Berlin
      - PASSWORD=admin
      - SUDO_PASSWORD=admin
    volumes:
      - ./config:/config
    ports:
      - 8440:8443
    restart: unless-stopped
networks:
  webdock-network:
    external: true