services:
  webdock-ui:
    container_name: webdock-ui
    build: .
    ports:
      - "8585:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose:ro
      - ${WEBDOCK_INSTALL_DIR:-/home/webDock}:/app/webdock
      - ${WEBDOCK_INSTALL_DIR:-/home/webDock}/docker-templates:/app/docker-templates
      - ${WEBDOCK_INSTALL_DIR:-/home/webDock}/docker-compose-data:/app/docker-compose-data
      - ./src/static/img:/app/static/img
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - CONFIG_DIR=/app/docker-compose-data/config
      - WEBDOCK_BASE_PATH=/app/webdock
      - COMPOSE_FILES_DIR=/app/docker-templates
      - COMPOSE_DATA_DIR=/app/docker-compose-data
    restart: unless-stopped
    networks:
      - webdock-network

volumes:
  host-config:

networks:
  webdock-network:
    external: true
