version: "3"

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    volumes:
      - /var/lib/openhab/backups:/srv
      - ./database/filebrowser.db:/database/filebrowser.db
      - ./settings.json:/config/settings.json
    ports:
      - 8998:80
    environment:
      - TZ=Germany/Berlin
      - PUID=1000
      - PGID=1000
    restart: unless-stopped