categories:
  - id: "smart_home"
    name: "Smart Home"
    icon: "fa-home"
    description: "Complete Smart Home automation and IoT control"
    containers:
      - name: "homeassistant"
        description: "Open-source platform for home automation, integrating various smart devices."
      - name: "openhab"
        description: "Vendor-agnostic automation software supporting numerous technologies and devices."
      - name: "mosquitto-broker"
        description: "Lightweight MQTT broker for IoT messaging."
      - name: "raspberrymatic"
        description: "Open-source alternative for HomeMatic central units, compatible with Raspberry Pi."
      - name: "zigbee2mqtt"
        description: "Bridge for connecting Zigbee devices to MQTT networks."
      - name: "homebridge"
        description: "Enables HomeKit support for non-native smart devices."
      - name: "node-red"
        description: "Visual programming tool for IoT automation and flows."
      - name: "bambucam"
        description: "Service for streaming Bambuser cameras."

  - id: "monitoring"
    name: "Monitoring"
    icon: "fa-line-chart"
    description: "Comprehensive system and network monitoring"
    containers:
      - name: "grafana"
        description: "Comprehensive analytics and monitoring solution for visualizing data."
      - name: "prometheus"
        description: "Monitoring system with a built-in time series database."
      - name: "nodeexporter"
        description: "Exports hardware and OS metrics to Prometheus."
      - name: "wud"
        description: "Watches for Docker updates."
      - name: "dozzle"
        description: "Real-time Docker logs viewer."
      - name: "uptime-kuma"
        description: "Self-hosted tool for monitoring uptime."
      - name: "frontail"
        description: "Web-based log streaming service."
      - name: "influxdb-arm"
        description: "Time series database optimized for ARM systems."
      - name: "influxdb-x86"
        description: "Time series database for x86 systems."

  - id: "network"
    name: "Network"
    icon: "fa-sitemap"
    description: "Network management and monitoring tools"
    containers:
      - name: "watchyourlan"
        description: "Detects network device presence on x86 systems."
      - name: "watchyourlanarm"
        description: "Detects network device presence on ARM systems."
      - name: "portainer"
        description: "User-friendly Docker management interface."
      - name: "homepage"
        description: "Modern application dashboard and start page."
      - name: "heimdall"
        description: "Application dashboard and service organizer."
      - name: "dockge"
        description: "Docker compose stack manager."

  - id: "development"
    name: "Development"
    icon: "fa-code"
    description: "Development environments and tools"
    containers:
      - name: "codeserver"
        description: "Runs VS Code in a web browser."
      - name: "filestash"
        description: "Web-based file manager supporting multiple protocols."
      - name: "filebrowser"
        description: "Simple web-based file browser."

  - id: "media"
    name: "Media"
    icon: "fa-picture-o"
    description: "Media streaming and management"
    containers:
      - name: "jellyfin"
        description: "Free media system for organizing and streaming media."
      - name: "paperless-ngx"
        description: "Document management system with OCR capabilities."
      - name: "scrypted"
        description: "Platform for home automation and smart camera management."
      - name: "hoarder"
        description: "Manager for media collections."
      - name: "spoolman"
        description: "Manager for 3D printer filament."

  - id: "system"
    name: "System"
    icon: "fa-server"
    description: "System services and management tools"
    containers:
      - name: "webdock-ui"
        description: "Web interface for managing Docker containers and services."

  - id: "imported"
    name: "Imported"
    icon: "fa-cloud-download-alt"
    description: "Manually imported containers"
    containers: []
