categories:
  smart_home:
    name: "Smart Home"
    icon: "fa-home"
    description: "Home automation and IoT containers"
    containers:
      - homeassistant
      - openhab
      - mosquitto
      - raspberrymatic
      - zigbee2mqtt
      - homebridge

  monitoring:
    name: "Monitoring"
    icon: "fa-chart-line"
    description: "System and network monitoring tools"
    containers:
      - grafana
      - prometheus
      - node_exporter
      - wud

  network:
    name: "Network"
    icon: "fa-network-wired"
    description: "Network management and monitoring"
    containers:
      - watchyourlan
      - portainer

  development:
    name: "Development"
    icon: "fa-code"
    description: "Development tools and environments"
    containers:
      - codeserver
      - filestash

  system:
    name: "System"
    icon: "fa-cogs"
    containers:
      - "webdock-ui"
      - "portainer"

  imported:
    name: 'Imported'
    icon: 'fa-download'
    description: 'Manually imported containers'
    containers: [] 