
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    networks:
      - webdock-network
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  webdock-network:
    external: true