services:
    scrypted:
        volumes:
            - ./data:/server/volume
        container_name: scrypted
        restart: unless-stopped
        network_mode: host
        image: ghcr.io/koush/scrypted

        # logging is noisy and will unnecessarily wear on flash storage.
        # scrypted has per device in memory logging that is preferred.
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
