version: "3"
services:
  influxdb:
    # Debian X86 Image
    image: influxdb:1.8.10
    container_name: influxdb
    restart: always
    volumes:
      - ./data:/var/lib/influxdb
    ports:
      - "8086:8086"