name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Copy files to build context
      run: |
        mkdir -p ./docker-compose-data/webdock-ui/docker-compose-files
        cp -r ./docker-compose-files/* ./docker-compose-data/webdock-ui/docker-compose-files/

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./docker-compose-data/webdock-ui
        file: ./docker-compose-data/webdock-ui/Dockerfile
        push: true
        tags: bangertech/webdock:latest
