services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    networks:
      - webdock-network    
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
    ports:
      - 5678:5678
    volumes:
      - ./n8n_storage:/home/node/.n8n
volumes:
  n8n_data:

networks:
  webdock-network:
    external: true